const Product = require('../../domain/entities/product.entity');

class ProductService {
    constructor(productRepository) { // ¡Depende de la interfaz!
        this.productRepository = productRepository;
    }

    async getAllProducts() {
        return this.productRepository.getAll();
    }

    async getProductById(id) {
        return this.productRepository.getById(id);
    }

    async createProduct(productData) {
        // Aquí podría haber lógica de negocio y validaciones
        const productEntity = new Product(
            null, // ID is null because it will be generated by the database
            productData.name,
            productData.description,
            productData.price,
            productData.stock,
            productData.category,
            productData.imageUrl
        );
        return this.productRepository.create(productEntity);
    }

    async updateProduct(id, productData) {
        const productEntity = new Product(
            id,
            productData.name,
            productData.description,
            productData.price,
            productData.stock,
            productData.category,
            productData.imageUrl
        );
        return this.productRepository.update(id, productEntity);
    }

    async deleteProduct(id) {
        return this.productRepository.delete(id);
    }
}
module.exports = ProductService;